### ISSUE TITLE
template scoped

### ISSUE THREAD

**Issue by quteam** [ktsn/vue-template-loader#48] opened 2018-03-12 13:23 UTC
Can I support separate component scopes options?  like this
`import withRender from './main.vue.tpl?scoped&style=./style.less';`

**Comment by ktsn** [comment] 2018-03-12 13:30
Duplicate of #19 
I'm unwilling to introduce this query trick other than `style` since it will be easily complicated the both user land import statement and internal complexity.

**Closed by ktsn** 2018-03-12 13:30 UTC
